### PR TITLE
Initial attempts at merger

### PR DESCRIPTION
**Pull request by staalmannen**
This is an initial attempt at merger between gqt and gtk-made-qt.
Interestingly, there are several things that are not overlapping, so the sum might be greater than the parts.

At this moment, the gtk-made-qt tests build. The aim is for the gqt tests to build, which are "vanilla" gtk applications. Still some issues with glib types.

For the future, more integration needed (now in 2 different "styles")

### CODE REVIEW

**Comment by e8johan** [comment]
I like the contents of the patch, but I would prefer if you could spend some time harmonizing the copyright headers. I think that everything is GPLv2 (examples might be BSD), but the copyright headers look a bit strange in some files and are missing from others.

Does that sound ok? Or would you like me to help out clearing up this?

**Comment by staalmannen** [comment]
I am going to try to do some harmonizing later, some of the important things are a bit adressed below. When it comes to licensing, this is ofcourse up to you and other authors. Personally, I think it would make sense to make the "libgt" into a static library (so that gtk-made-qt is only a build-time dependency, not a run-time dependency) and then perhaps LGPL2+ with static linking exception would make sense?

My first priority is to get the gqt tests to build again. I have made glib inclusion optional, and I am now fighting with what I believe to be some Qt4-to-Qt5 migrations in the gqt code (QObject does not contain certain classes used in gtk_window.h for example).

For the harmonization, I think it would be important with a "higher level" design decision:
Where should functions primarily be located? At this moment, I have as a rule-of-thumb removed redundant functions from gqt when present in gtk-made-qt. On the other hand, I think it makes it easier to read if gtk functions are located in their respective header and only "special functions" in custom headers like gtk-made-qt.h. Another nice thing with having a gtk-like header structure is that code might compile without any source modifications.

Third, I think I should somehow credit @rburchell for the first 2 commits, which are straight copying from the gqt code.

This pull request can remain open until we feel that everything looks OK - it will update automatically.

**Comment by rburchell** [comment]
Interesting to see some work on this. A long time since I have seen it :)

I have no stipulations or requirements on license for the code I wrote here. Anything is fine by me, so just go ahead and make whatever change you see fit.

For attribution, I'm fine with a mention in the copyright headers (if I touched a file significantly), but I don't need more than that.

I have no technical comments to make, as it's been way too long since I looked into this stuff, and I have no time or desire to work on it anymore - unfortunately.

**Comment by e8johan** [comment]
I too am happy to support any licensing scheme that we see fit (including changing the license). Doing an LGPLv2 + exception for allowing static linking might not help though, as Qt does not allow static linking, but if you view it as beneficial, I'm happy to accept such a merge request.

**Comment by staalmannen** [comment]
If static linking is impossible, the license is of less importance. I am not enough of an expert to say whether LGPL might give less problems than plain GPL when it comes to dynamic libraries though.

I will first look at the real problems (get gqt into qt5 and build tests, integrate code in a reasonable manner, ...).

So for "aesthetics" - do you guys prefer collecting as much as possible in gtk-made-qt.h or to move it into the gtk headers?

**Comment by staalmannen** [comment]
By the way: I noticed that libQt5UiTools only existed as an .a library ... so there is static linking also in Qt ;)

**Comment by staalmannen** [comment]
So I believe that the merger is getting into shape. Since it works to link libgq statically, I made this as default (simply because it would mean that one could distribute a binary that only depends on standard Qt libraries as run-time dependencies).

I have added LGPL2.1+static linking exception as license and added license headers to all source files except those found in examples. This change can definitely be reversed if you have any objections.
For those found in examples, I do not know what the licensing/copyright status is (if they were copied from a gtk test suite or so)

for future TODOs (can be in another pull request) is to solve some type conflict issues between QAction and QWidget for menu tests (need to learn more about Qt). Also, some tests compile but crash when executed... so some debugging will be needed.

Edit: So basically I went ahead with some invasive changes without official decision... in accordance with the motto "Lättare att få förlåtelse än tillåtelse" ;)

**Comment by e8johan** [comment]
Ok, I'm good to merge this. However, just one last iteration over the licensing choice. I am not opposed to the license proposed, but it is not something that you can hope to get into Qt.

Qt is available under GPLv2, GPLv3, LGPLv2.1 and LGPLv3, where the general trend is to move towards the v3 versions. These come with no static linking exception. I.e. all Qt libraries need to be linked dynamically unless you want your code to be affected by the GPL.

So, if you are still happy with the license you've picked, I'll press the big green button. I just want a final confirmation.

**Comment by staalmannen** [comment]
Cool!
I am not "religious" about licences as such and LGPLv3 could also be an option. I explicitly changed the static linking exception from the "0mq" (http://zeromq.org/area:licensing) to the GNU classpath (https://www.gnu.org/software/classpath/license.html) variant because the GNU classpath exception is not viral and LGPL+exception can thus be redistributed as plain LGPL (so if it would get into Qt it could just loose its exception without any permission needed from the authors). With the GNU classpath wording, one can even use plain GPL since it actually removes the issue of linking also dynamically.

To make it clearer, I could put the exception in a separate file. Also, if you prefer LGPLv3 I can change that too. I think it is most important that _you_ are comfortable with the license.

The reason I would like to make sure that static linking does not cause problems is mostly as a packager convenience. If I would like to re-compile an open source program and distribute it, it would be nice that it only depends on standard Qt libraries and that gtk-made-qt is not a runtime dependency (it also clarifies the role of gtk-made-qt as a porting tool and not as a drop-in runtime replacement of gtk libraries). The issue is however if a program is licenced under a GPL incompatible variant (MPL, CCDL, Apache...), then static linking could end up illegal.

**Comment by e8johan** [comment]
I completely buy your reasoning. Merged!

And thank you for your contribution. I'm glad to see someone actually using this stuff!

**Pull request merged**
